Develop
oscarnava/responsive-design pull request #1
Opened 2019-07-29 17:55 UTC by oscarnava

2019-07-29 19:07 UTC, mosaaleb commented
Reviewing

2019-07-29 20:32 UTC, mosaaleb requested changes
## Great job @oscarnava  @nicolasmarino99 :clap:. The UI looks very clean. Good use of semantic html tags. You have already handled most of the requirements, yet there's some minor requirements to be met before moving on.

Please see my comments below. 


### Navigation bar
- [x] should use fixed position.

### Latest News section
![Screenshot from 2019-07-29 22-15-08](https://user-images.githubusercontent.com/4246637/62079118-57b23200-b24e-11e9-8fe8-bbab78451cf5.png)

- [x] Each article should have an image on the leftmost part of the article and its title on the right side -- as seen on the TNW page (The text under the title should be aligned with the title)

### Footer
- [ ] The bottom part of the footer should have the TNW logo with a copyright paragraph -- as seen on TNW page.


### General
- [x] Let's add links to anything needs to be a link (articles - articles headers) -- As seen on TNW page.
- [x] The hamburger icon (bars) should not appear on medium nor big screens.


Please make sure that these requirements are done and request a new code review. 

#### Happy Coding :computer:

2019-07-29 20:32 UTC, mosaaleb commented on styles/styles.css
> +    grid-template-areas: "icon top-nav" "icon bottom-nav";
For more readability, let's put all styles that related to `1024px` breakpoint into the same block, also for `768px`

2019-07-30 22:40 UTC, Oghenebrume50 commented
**reviewing....**

2019-07-31 17:01 UTC, merged